Rate limiting will apply to any paths that have been configured (by default all paths). You can control the rate limiter configuration for any given controller or method as well as exclude any controller or method from being rate limited.

== Rate Limit Configurations

Each implementation will provide a way to supply rate limiting configurations. To use a given configuration for a section of your API, simply add the ann:ratelimiter.annotation.RateLimit[] annotation to the controller or method and supply the configuration name. For example:

snippet::example.RateLimitController[project="docs-examples"]

<1> The annotation is controlling which configuration will apply to this controller. The annotation can also be applied to individual methods for finer control
<2> The controllers path matches one of the configured paths
<3> The ann::ratelimiter.annotation.NoRateLimit[] annotation is being used to denote this controller should not be rate limited, even though its path does match one of the configured paths


The ann::ratelimiter.annotation.NoRateLimit[] can also be used at the controller level:

snippet::example.NoRateLimitController[project="docs-examples"]
